# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30f2db2f5a37d14e7966e63c1267670513c7bee003847b72328f46b98b72fb1ebdd3165736c6830752f017a9bc8958bd1fc9b94b9493a773b8e7fa0a8e297fe

test:
  secret_key_base: 1ea91df8517f483dce8575b487be16d54fd8fd33bd1f202ea9f563bf3ca98926981da1f5ffd26c3ee7e7f97b6ae5d95d89ba8cac5734c7cb981cf6551c8be196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
